apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1  # 실행할 MySQL 인스턴스 수
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      nodeSelector:
        app: backend
      containers:
        - name: mysql
          image: mysql:latest  # MySQL 최신 이미지
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "1234"  # MySQL 루트 비밀번호
            - name: MYSQL_DATABASE
              value: "mydb"  # 자동으로 생성할 데이터베이스 이름
          ports:
            - containerPort: 3306  # MySQL 포트
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306  # 외부에서 접근할 포트
      targetPort: 3306  # 컨테이너 내부 MySQL 포트
  type: ClusterIP  # 클러스터 내부에서만 접근 가능
